server:
  address: localhost
  port: 18080

spring:
  application:
    name: ERP Basic Management Module
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    generate-ddl: true
    database: mysql
  boot:
    admin:
      client:
        url: http://localhost:8080
        username: sergey
        password: sergey
        instance:
          metadata:
            user:
              name: ${spring.security.user.name}
              password: ${spring.security.user.password}
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/test?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
      maximum-pool-size: 4
  secondary:
    datasource:
      jdbc-url: jdbc:mysql://localhost:3306/test?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
      maximum-pool-size: 4
  hsqldb:
    datasource:
      url: jdbc:mysql://localhost:3306/test?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
  session:
    store-type: redis
    redis:
      flush-mode: on_save
  redis:
    host: 127.0.0.1
    password: 7887   # 문자는 ''안에 해야하는데 숫자는 따옴표 없어도 관련 없는듯 하다.
    port: 6379
#    lettuce:
#      pool:
#        max-active: 10
#        max-idle: 10
#        min-idle: 2



  security:
    user:
      name: sergey
      password: sergey
      roles: manager
#management:
#  endpoint:
#    health:
#      show-details: always
#  endpoints:
#    web:
#      exposure:
#        include: "*"


